service:
  name: profile-chat-api

plugins:
  - serverless-webpack
  - serverless-plugin-warmup
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-northeast-2
  state: dev
  memorySize: 128
  timeout: 10
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: '*'

functions:
  RootHandler:
    warmup: true
    handler: src/RootHandler.default
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{any+}
          method: ANY

custom:
  warmup:
    schedule: rate(5 minutes)
    cleanFolder: false
    memorySize: 128
    timeout: 30
    prewarm: true
  customDomain:
    domainName: profile-chat-api.anpaul0615.com
    stage: ${self:provider.stage}
    certificateName: '*.anpaul0615.com'
    createRoute53Record: true